apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport
spec:
  type: NodePort
  selector:
    app: Sudham
  ports:
    - name: firstport
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
