apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resourcequota
  namespace: my-namespace
spec:
  hard:
    pods: 4
    requests.cpu: 1
    requests.memory: 2Gi
    limits.cpu: 2
    limits.memory: 4Gi