apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: web-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx-group
  template:
    metadata:
      labels:
        app: nginx-group
    spec:
      containers:
      - name: nginx-new
        image: nginx
      tolerations:
        - key: "env"
          operator: "Equal"
          value: "prod"
          effect: "NoSchedule"  
