apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: Sudham
  template:
    metadata:
      name: jenkins
      labels:
        app: Sudham
    spec:
      containers:
        - name: myjenkins
          image: jenkins:2.60.1
