apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jenkins-deploy
spec:
  selector:
    matchLabels:
      app: Sudham
  replicas: 3
  template: 
    metadata:
      labels:
        app: Sudham
    spec:
      affinity:
        podAntiAffinity:
          prefferedDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - Sudham
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 80

          
